### ISSUE TITLE
Final Project: Enzyme-Kinetics---Activation-Model

### ISSUE THREAD

**Issue by MCGhetu** [szabgab/wis-python-bootcamp-2023-12#43]
Link to the final project: https://github.com/MCGhetu/Enzyme-Kinetics---Activation-Model/tree/main

**Comment by szabgab** [comment]
Nice.

* There should be instructions in the README on how to run the tests and how to run the code.
* I ran `pytest` and got this error:

```
E       AssertionError: False is not true : Excel file 'example.xlsx' does not exist.

test_activation_mechanism.py:34: AssertionError
```

* There should be a `.gitignore` file listing all the files and folder you want to exclude from git to make sure they are not added accidentally . e.g.
```
__pycache__/
```

* I ran `python activation_fit.py ` and got:

```
FileNotFoundError: [Errno 2] No such file or directory: 'example.xlsx'
```

Oh I see, the problem is that the Windows filesystem is case insensitive and the name of the actual file in `Example.xlsx`, but Linux and macOS are case sensitive so for me `Example.xlsx` is not the same as `example.xlsx`. After renaming Example.xlsx to example.xlsx both test and code started to work.

* The application should **not** assume the name of the input file. It should get it from the user somehow. (with the test it is ok, but it has to be the right case)

* The `main` function is way too long. It should be split up into smaller functions.
