### ISSUE TITLE
Maya Levy Greenberg- Final Project

### ISSUE THREAD

**Issue by MayaLevy2** [szabgab/wis-python-bootcamp-2023-12#47]
(https://github.com/MayaLevy2/Pump-Probe-Analysis)

**Comment by szabgab** [comment]
The user should not need to read the source code to find out the parameters and the user should never be asked to change the values in the code.

Running `pytest` did not run any of the tests. This is because the filename is `test.py` it should start with `test_`, eg. it should be `test_something.py`.

There is no `requirements.txt` listing the dependencies. After I renamed the test file and ran pytest I got:

```
ImportError while importing test module '/home/gabor/work/Pump-Probe-Analysis/test_a.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_a.py:3: in <module>
    from Fitting_Functions import lorentzian, fluorescence
Fitting_Functions.py:4: in <module>
    import nptdms
E   ModuleNotFoundError: No module named 'nptdms'
```

Also

```
$ python main.py 
Traceback (most recent call last):
  File "/home/gabor/work/Pump-Probe-Analysis/main.py", line 1, in <module>
    from Plotting_Functions import *
  File "/home/gabor/work/Pump-Probe-Analysis/Plotting_Functions.py", line 6, in <module>
    from Fitting_Functions import *
  File "/home/gabor/work/Pump-Probe-Analysis/Fitting_Functions.py", line 4, in <module>
    import nptdms
ModuleNotFoundError: No module named 'nptdms'
```

There is no `.gitignore` file.


Please fix these issues, push it out to github and comment here so I can get notified and I can check it.

**Comment by MayaLevy2** [comment]
sorry for the misunderstanding.
Hope it's better now.

**Comment by szabgab** [comment]
* The `requirements.txt` should only include the names of the packages, not explanation.
* The `math` package comes with python. it should **not** be listed.
* It is not a good idea to import with `*`, better list explicitly what you import `from Plotting_Functions import plot_all and import only what you really need in that file.
* Nice having reasonable length functions
