### ISSUE TITLE
Rain Analyzer - Gabriel Bar-Sella

### ISSUE THREAD

**Issue by gavrielbs** [szabgab/wis-python-bootcamp-2023-12#54]
https://github.com/gavrielbs/RainAnalyzer/tree/main

**Comment by szabgab** [comment]
* `requirements.txt` should only contain the names of the packages, not instructions and it should **not** contain packages that come with python such as the `os` package.
* Also you need 'scikit-learn' instead of 'sklearn'
* In the readme write `pip install -r requirements.txt` instead of duplicating the list of packages.
* Test file need to be called `test_something.py`
* Test functions must be called `test_something` to work
* generated files should **not** be in git. Now I have two modified files: `plots/correlation_matrix.png` and `plots/rain_graph.png`
* `__pycache__` should be listed in `.gitignore`
* There is a file generated called `plots/{target} over time.png` that seems to be a bug.
* Run `black` on your code!
